In [1]:
from openbb_terminal.sdk import openbb
import pandas as pd
import numpy as np

%matplotlib inline

2023-05-30 20:29:05.740515: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

# Indicies df

In [17]:
data_indicies = openbb.economy.indices()
data_indicies[["Chg", "%Chg"]] = data_indicies[["Chg", "%Chg"]].apply(pd.to_numeric)
data_indicies = data_indicies.set_index(data_indicies.columns[0])
data_indicies

                          Price    Chg  %Chg

DJIA                   33042.78 -50.56 -0.15
Nasdaq Composite       13017.43  41.74  0.32
S&P 500                 4205.52   0.07  0.00
DJ Total Stock Market  41879.22   2.63  0.01
Russell 2000            1767.29  -5.73 -0.32
NYSE Composite         14994.64 -84.05 -0.56
Barron's 400             910.21  -4.32 -0.47
CBOE Volatility           17.46  -0.49 -2.73
DJIA Futures              33061 -28.00 -0.08
S&P 500 Futures         4215.25   0.25  0.01

In [18]:
def highlight_max(cell):
    if type(cell) != str and cell < 0 :
        return 'background: red; color:black'
    else:
        return 'background: green; color: white'
  
data_indicies.style.applymap(highlight_max)

In [ ]:
# Dropdown to select chart for each index, would like this to the right of the heatmap in app

# Commodities

In [19]:
data_commodities = openbb.economy.futures()
data_commodities[["Chg", "%Chg"]] = data_commodities[["Chg", "%Chg"]].apply(pd.to_numeric)
data_commodities = data_commodities.set_index(data_commodities.columns[0])
data_commodities

                             Price     Chg  %Chg

Crude Oil                    69.47  0.0100  0.01
Brent Crude                  73.75  0.0400  0.05
Gold                       1978.00  0.9000  0.05
Silver                      23.290  0.0510  0.22
Natural Gas                  2.310 -0.0170 -0.73
Unleaded Gasoline           2.4835  0.0043  0.17
Copper                      3.6590 -0.0040 -0.11
Corn                        592.00 -2.0000 -0.34
Wheat                       585.75 -5.2500 -0.89
Bloomberg Commodity Index    98.33 -1.7500 -1.75

In [20]:
data_commodities.style.applymap(highlight_max)